#! /usr/bin/python3

"""myip.py

Usage:
    myip.py [-havqd46] [-l PERIOD] [-T] [--loop PERIOD] [-u --url URL]

Options:

    -h --help       Show this screen
    -v --version    Show version
    -6 --six        Show the IPv6 address 
    -4 --four       Show the IPv4 address only
    -q --quiet      Return only the address
    -l --loop       Run in a loop
    -d --debug      Run in debug mode
    -T              Print timestamp  
    -a              Print arguments
    -u --url        get ip from this link
    
"""

from lib.docopt import docopt
from getip import getip
import datetime
import time
from decimal import Decimal

arguments = docopt(__doc__, version='0.0.1')

def loop(PERIOD):
    while quit is False:
        start = time.time()
        print("Start: " + time.strftime("%H:%M:%S"))
        print(getip())
        
        time.sleep(PERIOD)


# Run main 

#TODO arrange "if logic in a more sensible order i.e. -l maybe needs to be last"

if __name__ == "__main__":
    if arguments['-q'] is True:
        print(getip())
    
    elif arguments['-l'] or arguments['--loop']is True:
        print("loop")  
        print("RUN IN A LOOP")
        try:
            print(Decimal(arguments['PERIOD']))
        except :
            print("I need a number!!")
        #loop(arguments['PERIOD'])
       
    
    elif arguments['-d']:
        print("******** Debug MODE **********")
        print(arguments)
    
    elif arguments['-T']:
        print('Timestamp: ' + time.strftime("%D %H:%M:%S") + getip()) 
    else: 
        print(getip())
        
